
import type { Point } from './types';

export const CATALOG_POINTS: Point[] = [
  // --- Goiânia ---
  {
    id: 1,
    title: 'Ponto Avançado - Goiânia Shopping',
    location: 'Av. T-10, 1300',
    neighborhood: 'Setor Bueno',
    city: 'Goiânia, GO',
    category: 'Shopping Center',
    images: [
        'https://images.unsplash.com/photo-1519567241046-7f570eee3c9e?q=80&w=800&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1567449303078-57ad995bd30f?q=80&w=800&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=800&auto=format&fit=crop'
    ],
    footTraffic: 'Alto',
    description: 'Espaço estratégico localizado na praça de alimentação do Goiânia Shopping. Ideal para captar clientes de alto poder aquisitivo.',
    features: ['Wi-Fi', 'Mobiliário incluso', 'Segurança 24h'],
    rentalOptions: [
      { period: 'Quinzenal', price: 1200 },
      { period: 'Mensal', price: 2000 },
      { period: 'Trimestral', price: 5500 },
    ],
  },
  {
    id: 2,
    title: 'Stand Promocional - Pão de Açúcar',
    location: 'R. 139, 230',
    neighborhood: 'Setor Marista',
    city: 'Goiânia, GO',
    category: 'Supermercado',
    images: ['https://images.unsplash.com/photo-1578916171728-46686eac8d58?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Alto',
    description: 'Ponto na entrada principal do Pão de Açúcar Marista. Área nobre com grande fluxo de moradores locais.',
    features: ['Ponto de energia', 'Permitido banner', 'Acesso facilitado'],
    rentalOptions: [
      { period: 'Quinzenal', price: 1000 },
      { period: 'Mensal', price: 1800 },
      { period: 'Trimestral', price: 5000 },
    ],
  },
  {
    id: 3,
    title: 'Quiosque Aeroporto Santa Genoveva',
    location: 'Alameda 4, s/n',
    neighborhood: 'Jardim Guanabara',
    city: 'Goiânia, GO',
    category: 'Aeroporto',
    images: ['https://images.unsplash.com/photo-1530521954074-e64f6810b32d?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Médio',
    description: 'Área de desembarque. Perfeito para abordar clientes chegando à cidade em busca de investimentos.',
    features: ['Ambiente climatizado', 'Fluxo de executivos', 'Estacionamento'],
    rentalOptions: [
        { period: 'Quinzenal', price: 1000 },
        { period: 'Mensal', price: 1900 },
        { period: 'Trimestral', price: 5200 },
    ],
  },
  {
    id: 7,
    title: 'Espaço Gourmet - Coco Bambu',
    location: 'Av. Dep. Jamel Cecílio',
    neighborhood: 'Jardim Goiás',
    city: 'Goiânia, GO',
    category: 'Restaurante',
    images: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Alto',
    description: 'Ponto de recepção dentro de um dos restaurantes mais movimentados da cidade. Público familiar e executivo.',
    features: ['Valet Parking', 'Ambiente Sofisticado', 'Público A+'],
    rentalOptions: [
      { period: 'Quinzenal', price: 1600 },
      { period: 'Mensal', price: 2800 },
      { period: 'Trimestral', price: 7500 },
    ],
  },
  {
    id: 8,
    title: 'Corner Café - Doce Café',
    location: 'Rua 9',
    neighborhood: 'Setor Oeste',
    city: 'Goiânia, GO',
    category: 'Cafeteria',
    images: ['https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Médio',
    description: 'Pequeno espaço em cafeteria tradicional. Ótimo para conversas mais longas e apresentação de portfólio.',
    features: ['Wi-Fi Grátis', 'Mesas disponíveis', 'Ambiente calmo'],
    rentalOptions: [
      { period: 'Quinzenal', price: 600 },
      { period: 'Mensal', price: 1100 },
      { period: 'Trimestral', price: 3000 },
    ],
  },
  {
    id: 9,
    title: 'Lounge Bar - Bahrem',
    location: 'Rua 144',
    neighborhood: 'Setor Marista',
    city: 'Goiânia, GO',
    category: 'Bar e Pub',
    images: ['https://images.unsplash.com/photo-1514933651103-005eec06c04b?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Alto',
    description: 'Ação promocional na entrada de um dos bares mais badalados do Marista. Ideal para público jovem adulto.',
    features: ['Horário Noturno', 'Alta visibilidade', 'Público Jovem'],
    rentalOptions: [
      { period: 'Quinzenal', price: 1500 },
      { period: 'Mensal', price: 2500 },
      { period: 'Trimestral', price: 6800 },
    ],
  },
  {
    id: 10,
    title: 'Recepção Academia Smart Fit',
    location: 'Av. T-63',
    neighborhood: 'Setor Bueno',
    city: 'Goiânia, GO',
    category: 'Academia',
    images: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Alto',
    description: 'Balcão próximo às catracas. Fluxo constante de alunos durante todo o dia.',
    features: ['Fluxo contínuo', 'Público local', 'Espaço compacto'],
    rentalOptions: [
      { period: 'Quinzenal', price: 750 },
      { period: 'Mensal', price: 1300 },
      { period: 'Trimestral', price: 3500 },
    ],
  },
  {
    id: 11,
    title: 'Hall de Entrada - Hotel Mercure',
    location: 'Av. República do Líbano',
    neighborhood: 'Setor Oeste',
    city: 'Goiânia, GO',
    category: 'Hotel',
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Médio',
    description: 'Espaço no lobby do hotel. Excelente para captar turistas e profissionais a trabalho.',
    features: ['Ar condicionado', 'Sofás para espera', 'Segurança'],
    rentalOptions: [
      { period: 'Quinzenal', price: 1300 },
      { period: 'Mensal', price: 2200 },
      { period: 'Trimestral', price: 6000 },
    ],
  },
  {
    id: 12,
    title: 'Ponto - Drogasil 24h',
    location: 'Av. 85',
    neighborhood: 'Setor Marista',
    city: 'Goiânia, GO',
    category: 'Farmácia',
    images: ['https://images.unsplash.com/photo-1631549916768-4119b2e5f926?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Alto',
    description: 'Ponto externo coberto em farmácia de grande movimento e alto padrão.',
    features: ['24 horas', 'Estacionamento próprio', 'Visibilidade Av. 85'],
    rentalOptions: [
      { period: 'Quinzenal', price: 900 },
      { period: 'Mensal', price: 1600 },
      { period: 'Trimestral', price: 4500 },
    ],
  },

  // --- São Paulo (Base Nacional) ---
  {
    id: 13,
    title: 'Corredor VIP - Shopping Cidade Jardim',
    location: 'Av. Magalhães de Castro',
    neighborhood: 'Cidade Jardim',
    city: 'São Paulo, SP',
    category: 'Shopping Center',
    images: ['https://images.unsplash.com/photo-1567449303183-293f879c2849?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Médio',
    description: 'Localização premium em um dos shoppings mais luxuosos do Brasil. Público AAA.',
    features: ['Exclusividade', 'Segurança armada', 'Público Elite'],
    rentalOptions: [
      { period: 'Quinzenal', price: 2500 },
      { period: 'Mensal', price: 4500 },
      { period: 'Trimestral', price: 12000 },
    ],
  },
  {
    id: 14,
    title: 'Frente de Loja - Fogo de Chão',
    location: 'Rua Augusta',
    neighborhood: 'Jardins',
    city: 'São Paulo, SP',
    category: 'Restaurante',
    images: ['https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Alto',
    description: 'Ponto de espera na churrascaria. Grande fluxo de turistas e executivos.',
    features: ['Valet', 'Área Coberta', 'Alto fluxo no almoço'],
    rentalOptions: [
      { period: 'Quinzenal', price: 1600 },
      { period: 'Mensal', price: 3000 },
      { period: 'Trimestral', price: 8000 },
    ],
  },
  {
    id: 15,
    title: 'WeWork Berrini',
    location: 'Av. Eng. Luís Carlos Berrini',
    neighborhood: 'Brooklin',
    city: 'São Paulo, SP',
    category: 'Coworking',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Médio',
    description: 'Espaço no lounge principal. Conexão direta com startups e empresas de tecnologia.',
    features: ['Networking', 'Café liberado', 'Internet Ultra'],
    rentalOptions: [
      { period: 'Quinzenal', price: 1800 },
      { period: 'Mensal', price: 3200 },
      { period: 'Trimestral', price: 9000 },
    ],
  },

  // --- Rio de Janeiro ---
  {
    id: 16,
    title: 'Lobby - Copacabana Palace',
    location: 'Av. Atlântica',
    neighborhood: 'Copacabana',
    city: 'Rio de Janeiro, RJ',
    category: 'Hotel',
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Alto',
    description: 'Ponto histórico e turístico. Visibilidade internacional.',
    features: ['Luxo', 'Turismo', 'Ícone da cidade'],
    rentalOptions: [
      { period: 'Quinzenal', price: 2800 },
      { period: 'Mensal', price: 5000 },
      { period: 'Trimestral', price: 14000 },
    ],
  },
  {
    id: 17,
    title: 'Quiosque Orla Rio',
    location: 'Posto 9',
    neighborhood: 'Ipanema',
    city: 'Rio de Janeiro, RJ',
    category: 'Lazer e Parques',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Alto',
    description: 'Quiosque na areia. Abordagem descontraída com público de alta renda.',
    features: ['Ar livre', 'Vista mar', 'Alto fluxo fds'],
    rentalOptions: [
      { period: 'Quinzenal', price: 2000 },
      { period: 'Mensal', price: 3500 },
      { period: 'Trimestral', price: 9800 },
    ],
  },

  // --- Brasília ---
  {
    id: 18,
    title: 'Pier 21 - Praça Central',
    location: 'SCES Trecho 2',
    neighborhood: 'Asa Sul',
    city: 'Brasília, DF',
    category: 'Shopping Center',
    images: ['https://images.unsplash.com/photo-1519567241046-7f570eee3c9e?q=80&w=800&auto=format&fit=crop'],
    footTraffic: 'Alto',
    description: 'Shopping aberto à beira do lago. Público jovem e familiar.',
    features: ['Vista Lago', 'Eventos constantes', 'Praça de Alimentação'],
    rentalOptions: [
      { period: 'Quinzenal', price: 1100 },
      { period: 'Mensal', price: 2100 },
      { period: 'Trimestral', price: 5800 },
    ],
  },
];
